language: ruby
rvm:
  - 1.8.7
  - 1.9.3

bundler_args: --without production development

before_script:
  - "cp config/database-default.yml config/database.yml"
  - "rake db:create"
  - "bundle exec rake db:test:load db:test:prepare"

script: "bundle exec rake"
